site_name: Forscher*innen in Wikidata - MAK
nav:
  - Startseite: index.md
  -ReadMe: readme.md
  - Installation: installation.md
  - Daten: Data.md
  - Code: code.md
  - Workflow: Workflow.md
theme:
  name: material
